"""empty message

Revision ID: 1157e7bdd4fb
Revises: 
Create Date: 2022-12-12 09:09:12.852367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1157e7bdd4fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
