"""empty message

Revision ID: 83c66ba0b21f
Revises: b03e0f5fb46f
Create Date: 2022-12-12 09:11:07.804751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c66ba0b21f'
down_revision = 'b03e0f5fb46f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user3')
    # ### end Alembic commands ###
